services:
  # Database Services
  postgres:
    image: postgres:15-alpine
    container_name: edu-platform-postgres
    environment:
      POSTGRES_DB: eduplatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Changed from 5432 to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eduplatform-network

  redis:
    image: redis:7-alpine
    container_name: edu-platform-redis
    ports:
      - "6380:6379"  # Changed from 6379 to avoid conflicts
    networks:
      - eduplatform-network

  # Message Queue
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: edu-platform-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - eduplatform-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: edu-platform-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"  # Changed from 9092 to avoid conflicts
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - eduplatform-network

  # Backend Services
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: edu-platform-api-gateway
    ports:
      - "8090:8080"  # Changed from 8080 to 8090
    environment:
      JWT_SECRET: mySecretKey1234567890123456789012345678901234567890
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - redis
    networks:
      - eduplatform-network

  user-management-service:
    build:
      context: ./backend/user-management-service
      dockerfile: Dockerfile
    container_name: edu-platform-user-service
    ports:
      - "8091:8081"  # Changed from 8081 to 8091
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eduplatform
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: mySecretKey1234567890123456789012345678901234567890
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - eduplatform-network

  course-management-service:
    build:
      context: ./backend/course-management-service
      dockerfile: Dockerfile
    container_name: edu-platform-course-service
    ports:
      - "8092:8082"  # Changed from 8082 to 8092
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/eduplatform
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - eduplatform-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: edu-platform-frontend
    ports:
      - "3001:3000"  # Changed from 3000 to 3001
    environment:
      REACT_APP_API_URL: http://localhost:8090  # Updated to match new API Gateway port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - eduplatform-network

volumes:
  postgres_data:

networks:
  eduplatform-network:
    driver: bridge